levels = [
[ # W = Muro, E = Meta, P = Jugador 1, J = Jugador 2, H = Jugador 3, I = Jugador 4, 
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                              W",
"W                           J  W",
"W    P                         W",
"W                              W",
"W                              W",
"W                              W",
"WWWWWWW       WWW   WWWWWWWWWWWW",
"W                              W",
"W                              W",
"W         WWWWWWWWWWW          W",
"W                              W",
"W          O                   W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W   WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                             EW",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
],
[
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                              W",
"W                           J  W",
"W    P                         W",
"W       WWWWWWWWWWW            W",
"W                              W",
"W                              W",
"WWWWWWW       WWW   WWWWWWWWWWWW",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W         WWWWWWWWWWW          W",
"W                              W",
"W                 E            W",
"W                              W",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
],
[
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                              W",
"W        WWWWWWWWWWWWWWWWWW J  W",
"W    P                         W",
"W                              W",
"W             WWWWWWWWWWWWW    W",
"W                              W",
"WWWWWWW       WWW   WWWWWWWWWWWW",
"W                          E   W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W                              W",
"W         WWWWWWWWWWW          W",
"W     WWWWWWWWW                W",
"W                              W",
"W                              W",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

]